#!/bin/bash

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 6 > /tmp/homes.list

while read BASEDIR; do
	rm -rf "$BASEDIR/.config/menus/applications-merged/geogebra-classic.menu"
    rm -rf "$BASEDIR/.local/share/applications/geogebra-classic.desktop"
done < /tmp/homes.list