#!/bin/bash

function rmLaunch {
    rm -rf "$BASEDIR/.local/share/applications/$1.desktop"
    rm -rf "$BASEDIR/Desktop/$1.desktop" 2> /dev/null
}

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 6 > /tmp/homes.list

while read BASEDIR; do
    USUARIO=$(basename $BASEDIR)

    rmLaunch "celestia"
    
	while read APPSITEM; do
		if [ "$APPSITEM" != "" ]; then
			AppName=$(echo $APPSITEM | cut -d ',' -f 1)
			rmLaunch "$AppName"
		else
			echo ""
		fi
	done < /usr/share/appsedu/apps.conf

    runuser -l $USUARIO -c "rm -rf /home/$USUARIO/.cache/"
    if [ -f /usr/bin/lxpanelctl ]; then
        su - $USUARIO -c "lxpanelctl restart"
    fi
done < /tmp/homes.list