#!/bin/bash

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 1 > /tmp/homes.list

function geraShort {
	echo "[Desktop Entry]"
	echo "Type=Link"
	cat $1 | \
	grep "Name=" | head -n1
	cat $1 | \
	grep "Name[pt_BR]=" | head -n1
	cat $1 | \
	grep "Icon=" | head -n1
	echo "URL=$2"
}

function deployLaunch {
	runuser -l $USUARIO -c \
	"cp -rf /tmp/appsedu/$1.menu /home/$USUARIO/.config/menus/applications-merged/"
	runuser -l $USUARIO -c \
	"cp -rf /tmp/appsedu/$1.desktop /home/$USUARIO/.local/share/applications/"
	if [ "$2" != "noshort" ]; then
		geraShort /tmp/appsedu/$1.desktop \
		/home/$USUARIO/.local/share/applications/$1.desktop \
		> /home/$USUARIO/Desktop/$1.desktop
	fi
}

while read USUARIO; do
	runuser -l $USUARIO -c "mkdir -p /home/$USUARIO/.config/menus/applications-merged/"
	runuser -l $USUARIO -c "mkdir -p /home/$USUARIO/.local/share/desktop-directories/"
	
	runuser -l $USUARIO -c \
	"cp -rf /tmp/appsedu/education-Math.directory /home/$USUARIO/.local/share/desktop-directories/"
	runuser -l $USUARIO -c \
	"cp -rf /tmp/appsedu/education-Physics.directory /home/$USUARIO/.local/share/desktop-directories/"
	runuser -l $USUARIO -c \
	"cp -rf /tmp/appsedu/education-Chemistry.directory /home/$USUARIO/.local/share/desktop-directories/"
	runuser -l $USUARIO -c \
	"cp -rf /tmp/appsedu/education-Geography.directory /home/$USUARIO/.local/share/desktop-directories/"
	runuser -l $USUARIO -c \
	"cp -rf /tmp/appsedu/education-Computing.directory /home/$USUARIO/.local/share/desktop-directories/"
	runuser -l $USUARIO -c \
	"cp -rf /tmp/appsedu/education-Electronics.directory /home/$USUARIO/.local/share/desktop-directories/"
	runuser -l $USUARIO -c \
	"cp -rf /tmp/appsedu/education-Astronomy.directory /home/$USUARIO/.local/share/desktop-directories/"

	deployLaunch "org.kde.step"
	deployLaunch "geogebra-classic"
	deployLaunch "wxMaxima"
	deployLaunch "gresistor"
	deployLaunch "avogadro"
	deployLaunch "gchem3d-0.14" "noshort"
	deployLaunch "gchemcalc-0.14" "noshort"
	deployLaunch "gchempaint-0.14"
	deployLaunch "gelemental"
	deployLaunch "gspectrum-0.14" "noshort"
	deployLaunch "gchemtable-0.14"
	deployLaunch "org.kde.marble.maps" "noshort"
	deployLaunch "org.kde.marble-qt"
	deployLaunch "klavaro"
	deployLaunch "scratch"
	deployLaunch "logisim"
	deployLaunch "stellarium"

	runuser -l $USUARIO -c "rm -rf /home/$USUARIO/.cache/"
	if [ -f /usr/bin/lxpanelctl ]; then
		su - $USUARIO -c "lxpanelctl restart"
	fi
done < /tmp/homes.list